### ISSUE TITLE
Cambiar paleta de colores

### ISSUE THREAD

**Issue by Dra-Dany-12** [Zagarsix/Project-Dra-Dany#1]
Paleta de colores rosados

**Comment by Dra-Dany-12** [comment]
- Cambiar a paleta de colores: tonalidades púrpura.
- Agregando fondo "https://www.xtrafondos.com/wallpapers/3d-abstraccion-morado-7934.jpg"

**Comment by Zagarsix** [comment]
- Paleta de colores aplicada:
 /* 
purple
blueviolet
rgb(82, 1, 82)
   */

- Fondo aplicado.
