### ISSUE TITLE
Agregar Carrusel

### ISSUE THREAD

**Issue by Dra-Dany-12** [Zagarsix/Project-Dra-Dany#2]
CONTENIDO de las imágenes:
Imagen 1: Título: Mesoterapia con dermapen.
                 Descripción: Inyección de vitaminas, ácido hialurónico y coctéles.

Imagen 2: Título: Tapaduras blancas
                 Descripción: Cambio de amalgama por tapadura de resina, desde $ 40.000 

Imagen 3: Título: Aplicación de bótox
                 Descripción: Aplicación por zonas desde los $ 90.000

Imagen 4: Título: Odontopediatría
                 Descripción: Atención integral para niños desde el primer añito.

Nota: Imágenes adjuntadas en correo.

**Comment by Zagarsix** [comment]
- Carrusel creado según requerimientos.
- Imágenes y contenido adjuntado.
- Edición y escalado de imágenes.

* * Color de fuente queda sujeto a cambios, según necesidad del cliente.
